fix(build): Depend `libutil` in the `Main` library
After the refactoring in commit 340169a20e42ba53a33c3183319ff97e290d0242, the
build broke when using G++ compiler with a linker error:

> /usr/bin/ld: libmonomuxCore.a(Pty.cpp.o): in function `monomux::Pty::Pty()':
> /home/runner/work/monomux/monomux/src/system/Pty.cpp:42: undefined reference to `openpty'
> /usr/bin/ld: libmonomuxCore.a(Pty.cpp.o): in function `monomux::Pty::setupChildrenSide()':
> /home/runner/work/monomux/monomux/src/system/Pty.cpp:69: undefined reference to `login_tty'